export const CCKP_VARIABLES = [
  { id: 'tas',     label: 'Mean Temperature',        unit: '°C' },
  { id: 'tasmax',  label: 'Max Temperature',         unit: '°C' },
  { id: 'tasmin',  label: 'Min Temperature',         unit: '°C' },
  { id: 'pr',      label: 'Precipitation',           unit: 'mm/day' },
  { id: 'rx1day',  label: 'Rx1d (Max 1-day Precip)', unit: 'mm' },
  { id: 'rx5day',  label: 'Rx5d (Max 5-day Precip)', unit: 'mm' },
  { id: 'hurs',    label: 'Relative Humidity',       unit: '%' },
  { id: 'sfcWind', label: 'Wind Speed',              unit: 'm/s' },
];

export const CCKP_SCENARIOS = [
  { id: 'ssp126', label: 'SSP1-2.6 (Low)',          color: '#22c55e' },
  { id: 'ssp245', label: 'SSP2-4.5 (Intermediate)', color: '#f59e0b' },
  { id: 'ssp585', label: 'SSP5-8.5 (High)',          color: '#ef4444' },
];

// Maps ISO3 country code → CCKP watershed geocode prefix
// Actual CCKP prefixes (verified from live API):
//   EAP = East Asia & Pacific
//   SOA = South & Southeast Asia
//   ECA = Europe & Central Asia
//   LAC = Latin America & Caribbean
//   WCA = West & Central Africa
//   ESA = Eastern & Southern Africa
//   OTH = Other (used for MNA and some others)
export const COUNTRY_WS_REGION = {
  // East Asia & Pacific → EAP
  AUS:'EAP', CHN:'EAP', FJI:'EAP', IDN:'EAP', JPN:'EAP', KHM:'EAP',
  KIR:'EAP', KOR:'EAP', LAO:'EAP', MHL:'EAP', MMR:'EAP', MNG:'EAP',
  MYS:'EAP', NRU:'EAP', NZL:'EAP', PHL:'EAP', PLW:'EAP', PNG:'EAP',
  PRK:'EAP', SGP:'EAP', SLB:'EAP', THA:'EAP', TLS:'EAP', TON:'EAP',
  TUV:'EAP', VNM:'EAP', VUT:'EAP', WSM:'EAP',

  // South & Southeast Asia → SOA
  AFG:'SOA', BGD:'SOA', BTN:'SOA', IND:'SOA', LKA:'SOA',
  MDV:'SOA', NPL:'SOA', PAK:'SOA',

  // Europe & Central Asia → ECA
  ALB:'ECA', ARM:'ECA', AUT:'ECA', AZE:'ECA', BEL:'ECA', BGR:'ECA',
  BIH:'ECA', BLR:'ECA', CHE:'ECA', CYP:'ECA', CZE:'ECA', DEU:'ECA',
  DNK:'ECA', ESP:'ECA', EST:'ECA', FIN:'ECA', FRA:'ECA', GBR:'ECA',
  GEO:'ECA', GRC:'ECA', HRV:'ECA', HUN:'ECA', IRL:'ECA', ISL:'ECA',
  ITA:'ECA', KAZ:'ECA', KGZ:'ECA', LTU:'ECA', LUX:'ECA', LVA:'ECA',
  MDA:'ECA', MKD:'ECA', MLT:'ECA', MNE:'ECA', NLD:'ECA', NOR:'ECA',
  POL:'ECA', PRT:'ECA', ROU:'ECA', RUS:'ECA', SRB:'ECA', SVK:'ECA',
  SVN:'ECA', SWE:'ECA', TJK:'ECA', TKM:'ECA', TUR:'ECA', UKR:'ECA',
  UZB:'ECA', XKX:'ECA',

  // Latin America & Caribbean → LAC
  ARG:'LAC', BLZ:'LAC', BOL:'LAC', BRA:'LAC', CHL:'LAC', COL:'LAC',
  CRI:'LAC', CUB:'LAC', DOM:'LAC', ECU:'LAC', GTM:'LAC', GUY:'LAC',
  HND:'LAC', HTI:'LAC', JAM:'LAC', MEX:'LAC', NIC:'LAC', PAN:'LAC',
  PER:'LAC', PRY:'LAC', SLV:'LAC', SUR:'LAC', TTO:'LAC', URY:'LAC',
  VEN:'LAC', CAN:'LAC', USA:'LAC',

  // Middle East & North Africa → OTH (CCKP uses OTH prefix for this region)
  ARE:'OTH', BHR:'OTH', DZA:'OTH', EGY:'OTH', IRN:'OTH', IRQ:'OTH',
  ISR:'OTH', JOR:'OTH', KWT:'OTH', LBN:'OTH', LBY:'OTH', MAR:'OTH',
  OMN:'OTH', PSE:'OTH', QAT:'OTH', SAU:'OTH', SYR:'OTH', TUN:'OTH',
  YEM:'OTH',

  // West & Central Africa → WCA
  BEN:'WCA', BFA:'WCA', CAF:'WCA', CIV:'WCA', CMR:'WCA', COD:'WCA',
  COG:'WCA', CPV:'WCA', GAB:'WCA', GHA:'WCA', GIN:'WCA', GMB:'WCA',
  GNB:'WCA', GNQ:'WCA', LBR:'WCA', MLI:'WCA', MRT:'WCA', NER:'WCA',
  NGA:'WCA', SEN:'WCA', SLE:'WCA', STP:'WCA', TCD:'WCA', TGO:'WCA',

  // Eastern & Southern Africa → ESA
  AGO:'ESA', BDI:'ESA', BWA:'ESA', COM:'ESA', ERI:'ESA', ETH:'ESA',
  KEN:'ESA', LSO:'ESA', MDG:'ESA', MOZ:'ESA', MUS:'ESA', MWI:'ESA',
  NAM:'ESA', RWA:'ESA', SDN:'ESA', SOM:'ESA', SSD:'ESA', SWZ:'ESA',
  SYC:'ESA', TZA:'ESA', UGA:'ESA', ZAF:'ESA', ZMB:'ESA', ZWE:'ESA',
};

// Alphabetical country list
export const COUNTRIES = [
  { iso3:'AFG', name:'Afghanistan' },
  { iso3:'AGO', name:'Angola' },
  { iso3:'ALB', name:'Albania' },
  { iso3:'ARE', name:'United Arab Emirates' },
  { iso3:'ARG', name:'Argentina' },
  { iso3:'ARM', name:'Armenia' },
  { iso3:'AUS', name:'Australia' },
  { iso3:'AUT', name:'Austria' },
  { iso3:'AZE', name:'Azerbaijan' },
  { iso3:'BDI', name:'Burundi' },
  { iso3:'BEL', name:'Belgium' },
  { iso3:'BEN', name:'Benin' },
  { iso3:'BFA', name:'Burkina Faso' },
  { iso3:'BGD', name:'Bangladesh' },
  { iso3:'BGR', name:'Bulgaria' },
  { iso3:'BHR', name:'Bahrain' },
  { iso3:'BIH', name:'Bosnia & Herzegovina' },
  { iso3:'BLR', name:'Belarus' },
  { iso3:'BLZ', name:'Belize' },
  { iso3:'BOL', name:'Bolivia' },
  { iso3:'BRA', name:'Brazil' },
  { iso3:'BTN', name:'Bhutan' },
  { iso3:'BWA', name:'Botswana' },
  { iso3:'CAF', name:'Central African Republic' },
  { iso3:'CAN', name:'Canada' },
  { iso3:'CHE', name:'Switzerland' },
  { iso3:'CHL', name:'Chile' },
  { iso3:'CHN', name:'China' },
  { iso3:'CIV', name:"Côte d'Ivoire" },
  { iso3:'CMR', name:'Cameroon' },
  { iso3:'COD', name:'Congo, Dem. Rep.' },
  { iso3:'COG', name:'Congo, Rep.' },
  { iso3:'COL', name:'Colombia' },
  { iso3:'COM', name:'Comoros' },
  { iso3:'CPV', name:'Cabo Verde' },
  { iso3:'CRI', name:'Costa Rica' },
  { iso3:'CUB', name:'Cuba' },
  { iso3:'CYP', name:'Cyprus' },
  { iso3:'CZE', name:'Czechia' },
  { iso3:'DEU', name:'Germany' },
  { iso3:'DJI', name:'Djibouti' },
  { iso3:'DNK', name:'Denmark' },
  { iso3:'DOM', name:'Dominican Republic' },
  { iso3:'DZA', name:'Algeria' },
  { iso3:'ECU', name:'Ecuador' },
  { iso3:'EGY', name:'Egypt' },
  { iso3:'ERI', name:'Eritrea' },
  { iso3:'ESP', name:'Spain' },
  { iso3:'EST', name:'Estonia' },
  { iso3:'ETH', name:'Ethiopia' },
  { iso3:'FIN', name:'Finland' },
  { iso3:'FJI', name:'Fiji' },
  { iso3:'FRA', name:'France' },
  { iso3:'GAB', name:'Gabon' },
  { iso3:'GBR', name:'United Kingdom' },
  { iso3:'GEO', name:'Georgia' },
  { iso3:'GHA', name:'Ghana' },
  { iso3:'GIN', name:'Guinea' },
  { iso3:'GMB', name:'Gambia' },
  { iso3:'GNB', name:'Guinea-Bissau' },
  { iso3:'GNQ', name:'Equatorial Guinea' },
  { iso3:'GRC', name:'Greece' },
  { iso3:'GTM', name:'Guatemala' },
  { iso3:'GUY', name:'Guyana' },
  { iso3:'HND', name:'Honduras' },
  { iso3:'HRV', name:'Croatia' },
  { iso3:'HTI', name:'Haiti' },
  { iso3:'HUN', name:'Hungary' },
  { iso3:'IDN', name:'Indonesia' },
  { iso3:'IND', name:'India' },
  { iso3:'IRL', name:'Ireland' },
  { iso3:'IRN', name:'Iran' },
  { iso3:'IRQ', name:'Iraq' },
  { iso3:'ISL', name:'Iceland' },
  { iso3:'ISR', name:'Israel' },
  { iso3:'ITA', name:'Italy' },
  { iso3:'JAM', name:'Jamaica' },
  { iso3:'JOR', name:'Jordan' },
  { iso3:'JPN', name:'Japan' },
  { iso3:'KAZ', name:'Kazakhstan' },
  { iso3:'KEN', name:'Kenya' },
  { iso3:'KGZ', name:'Kyrgyz Republic' },
  { iso3:'KHM', name:'Cambodia' },
  { iso3:'KOR', name:'Korea, Rep.' },
  { iso3:'KWT', name:'Kuwait' },
  { iso3:'LAO', name:'Lao PDR' },
  { iso3:'LBN', name:'Lebanon' },
  { iso3:'LBR', name:'Liberia' },
  { iso3:'LBY', name:'Libya' },
  { iso3:'LKA', name:'Sri Lanka' },
  { iso3:'LSO', name:'Lesotho' },
  { iso3:'LTU', name:'Lithuania' },
  { iso3:'LUX', name:'Luxembourg' },
  { iso3:'LVA', name:'Latvia' },
  { iso3:'MAR', name:'Morocco' },
  { iso3:'MDA', name:'Moldova' },
  { iso3:'MDG', name:'Madagascar' },
  { iso3:'MDV', name:'Maldives' },
  { iso3:'MEX', name:'Mexico' },
  { iso3:'MKD', name:'North Macedonia' },
  { iso3:'MLI', name:'Mali' },
  { iso3:'MLT', name:'Malta' },
  { iso3:'MMR', name:'Myanmar' },
  { iso3:'MNE', name:'Montenegro' },
  { iso3:'MNG', name:'Mongolia' },
  { iso3:'MOZ', name:'Mozambique' },
  { iso3:'MRT', name:'Mauritania' },
  { iso3:'MUS', name:'Mauritius' },
  { iso3:'MWI', name:'Malawi' },
  { iso3:'MYS', name:'Malaysia' },
  { iso3:'NAM', name:'Namibia' },
  { iso3:'NER', name:'Niger' },
  { iso3:'NGA', name:'Nigeria' },
  { iso3:'NIC', name:'Nicaragua' },
  { iso3:'NLD', name:'Netherlands' },
  { iso3:'NOR', name:'Norway' },
  { iso3:'NPL', name:'Nepal' },
  { iso3:'NZL', name:'New Zealand' },
  { iso3:'OMN', name:'Oman' },
  { iso3:'PAK', name:'Pakistan' },
  { iso3:'PAN', name:'Panama' },
  { iso3:'PER', name:'Peru' },
  { iso3:'PHL', name:'Philippines' },
  { iso3:'PNG', name:'Papua New Guinea' },
  { iso3:'POL', name:'Poland' },
  { iso3:'PRK', name:'Korea, Dem. Rep.' },
  { iso3:'PRY', name:'Paraguay' },
  { iso3:'PSE', name:'West Bank & Gaza' },
  { iso3:'PRT', name:'Portugal' },
  { iso3:'QAT', name:'Qatar' },
  { iso3:'ROU', name:'Romania' },
  { iso3:'RUS', name:'Russia' },
  { iso3:'RWA', name:'Rwanda' },
  { iso3:'SAU', name:'Saudi Arabia' },
  { iso3:'SDN', name:'Sudan' },
  { iso3:'SEN', name:'Senegal' },
  { iso3:'SGP', name:'Singapore' },
  { iso3:'SLE', name:'Sierra Leone' },
  { iso3:'SLB', name:'Solomon Islands' },
  { iso3:'SLV', name:'El Salvador' },
  { iso3:'SOM', name:'Somalia' },
  { iso3:'SRB', name:'Serbia' },
  { iso3:'SSD', name:'South Sudan' },
  { iso3:'STP', name:'São Tomé & Príncipe' },
  { iso3:'SUR', name:'Suriname' },
  { iso3:'SVK', name:'Slovakia' },
  { iso3:'SVN', name:'Slovenia' },
  { iso3:'SWE', name:'Sweden' },
  { iso3:'SWZ', name:'Eswatini' },
  { iso3:'SYC', name:'Seychelles' },
  { iso3:'SYR', name:'Syria' },
  { iso3:'TCD', name:'Chad' },
  { iso3:'TGO', name:'Togo' },
  { iso3:'THA', name:'Thailand' },
  { iso3:'TJK', name:'Tajikistan' },
  { iso3:'TKM', name:'Turkmenistan' },
  { iso3:'TLS', name:'Timor-Leste' },
  { iso3:'TON', name:'Tonga' },
  { iso3:'TTO', name:'Trinidad & Tobago' },
  { iso3:'TUN', name:'Tunisia' },
  { iso3:'TUR', name:'Turkey' },
  { iso3:'TZA', name:'Tanzania' },
  { iso3:'UGA', name:'Uganda' },
  { iso3:'UKR', name:'Ukraine' },
  { iso3:'URY', name:'Uruguay' },
  { iso3:'USA', name:'United States' },
  { iso3:'UZB', name:'Uzbekistan' },
  { iso3:'VEN', name:'Venezuela' },
  { iso3:'VNM', name:'Vietnam' },
  { iso3:'VUT', name:'Vanuatu' },
  { iso3:'WSM', name:'Samoa' },
  { iso3:'XKX', name:'Kosovo' },
  { iso3:'YEM', name:'Yemen' },
  { iso3:'ZAF', name:'South Africa' },
  { iso3:'ZMB', name:'Zambia' },
  { iso3:'ZWE', name:'Zimbabwe' },
];
